 #Deploy aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
   replicas: 1
   selector:
     matchLabels:
       app: conversaotemperatura
   template:
     metadata:
       labels:
         app: conversaotemperatura
     spec:
       containers:
         - name: conversaotemperatura
           image: thiagogomestec/conversao-temperatura:latest
           ports:
             - containerPort: 8080
---
# Service da aplicação Web
apiVersion: v1
kind: Service
metadata:
  name: conversaotemperatura
spec: 
  selector:
    app: conversaotemperatura
  ports:
    - port: 8080
      targetPort: 8080
     # protocol: TCP
     # name: http
      nodePort: 30002
  type: LoadBalancer